'use client';

// Face OS architecture:
//
// User journey:
//   Face Identity → Face Condition → Face Design → Face Insight
//   (知る → 整える → 表現する → 蓄積から学ぶ)
//
// Face Intelligence (future, not implemented):
//   The knowledge layer generated by the entire Face OS ecosystem.
//   Anonymous knowledge from aggregated Face Insight records with explicit consent.
//   Consumed by brand programs, research, education, and future collaborations.
//   See types/karte.ts for full domain model.

import React, { useEffect, useState } from 'react';
import { ScanFace } from 'lucide-react';
import dynamic from 'next/dynamic';

import FaceOSNav from '@/components/FaceOSNav';
import HomeDashboard from '@/components/HomeDashboard';
import type { UserLevel } from '@/types/userLevel';

const TabDiagnosis   = dynamic(() => import('@/components/karte/TabDiagnosis'),   { ssr: false });
const FaceConditionPage = dynamic(() => import('@/components/karte/FaceConditionPage'), { ssr: false });
const TabDailyMakeup = dynamic(() => import('@/components/karte/TabDailyMakeup'), { ssr: false });
const TabHistory     = dynamic(() => import('@/components/karte/TabHistory'),     { ssr: false });
const PilotPage      = dynamic(() => import('@/components/pilot/PilotPage'),       { ssr: false });

type NavId = 'home' | 'identity' | 'condition' | 'design' | 'karte' | 'insight' | 'pilot';
type Gender = 'female' | 'male';

const NAV_LABELS: Record<NavId, string> = {
  home:      'ホーム',
  identity:  'あなたの顔の設計図',
  condition: '今日のセルフケア',
  design:    '今日のメイクの目的は？',
  karte:     '顔カルテ',
  insight:   '顔インサイト',
  pilot:     'ミス・ワールド パイロット',
};

export default function Home() {
  const [activeNav, setActiveNav] = useState<NavId>('home');
  const [gender, setGender]       = useState<Gender>('female');
  const [level, setLevel]         = useState<UserLevel>('advanced');

  // 参加者の専用リンク（?p=）はパイロットだけを表示する
  const [participantMode, setParticipantMode] = useState(false);
  useEffect(() => { if (new URLSearchParams(window.location.search).has('p')) setParticipantMode(true); }, []);

  const isMale = gender === 'male';

  if (participantMode) {
    return (
      <div className="min-h-screen bg-[#F7F1E8]">
        <header className="border-b border-stone-200/60 bg-white/90 backdrop-blur-sm">
          <div className="max-w-2xl mx-auto px-4 py-4 flex items-center gap-3">
            <div className="w-9 h-9 rounded-full flex items-center justify-center bg-gradient-to-br from-champagne/50 to-amber-100/60">
              <ScanFace className="w-5 h-5 text-gold" strokeWidth={1.5} />
            </div>
            <h1 className="text-sm font-semibold text-stone-900 tracking-tight">黄金比 Face OS</h1>
          </div>
        </header>
        <main className="max-w-2xl mx-auto px-4 py-6">
          <PilotPage />
        </main>
      </div>
    );
  }

  return (
    <div className={`min-h-screen transition-colors duration-300 ${isMale ? 'bg-[#F0EDE8]' : 'bg-[#F7F1E8]'}`}>
      <header className="border-b border-stone-200/60 bg-white/90 backdrop-blur-sm sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between gap-3">
          <div className="flex items-center gap-3 min-w-0">
            <div className={`w-9 h-9 rounded-full flex items-center justify-center flex-shrink-0 transition-colors duration-300 ${isMale ? 'bg-stone-800' : 'bg-gradient-to-br from-champagne/50 to-amber-100/60'}`}>
              <ScanFace className={`w-5 h-5 transition-colors duration-300 ${isMale ? 'text-white' : 'text-gold'}`} strokeWidth={1.5} />
            </div>
            <div className="min-w-0">
              <h1 className="text-sm sm:text-base font-semibold text-stone-900 tracking-tight leading-none truncate">
                黄金比 Face OS
              </h1>
              <p className="text-[9px] sm:text-[10px] text-stone-400 mt-0.5 tracking-wide hidden sm:block">
                黄金比フェイスカルテ — 顔を知り、整え、表現する
              </p>
            </div>
          </div>

          <div className="lg:hidden">
            <span className={`text-xs font-semibold ${isMale ? 'text-stone-700' : 'text-amber-700'}`}>
              {NAV_LABELS[activeNav]}
            </span>
          </div>
        </div>
      </header>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-6 flex gap-6">
        <FaceOSNav
          active={activeNav}
          onNavigate={setActiveNav}
          gender={gender}
          onGenderChange={setGender}
          level={level}
          onLevelChange={setLevel}
        />

        <main className="flex-1 min-w-0 pb-20 lg:pb-8">
          {activeNav === 'home' && (
            <HomeDashboard gender={gender} onNavigate={setActiveNav} />
          )}

          {activeNav === 'identity' && (
            <TabDiagnosis
              gender={gender}
              onBeginDesign={() => setActiveNav('design')}
              onDoneForToday={() => setActiveNav('home')}
            />
          )}

          {activeNav === 'condition' && (
            <FaceConditionPage onNavigate={(nav) => setActiveNav(nav as typeof activeNav)} />
          )}

          {activeNav === 'design' && (
            <TabDailyMakeup level={level} onNavigate={(nav) => setActiveNav(nav as typeof activeNav)} />
          )}

          {activeNav === 'karte' && (
            <TabHistory onNavigate={(nav) => setActiveNav(nav as typeof activeNav)} />
          )}

          {activeNav === 'insight' && (
            <InsightPlaceholder isMale={isMale} />
          )}

          {activeNav === 'pilot' && (
            <PilotPage />
          )}
        </main>
      </div>
    </div>
  );
}

function InsightPlaceholder({ isMale }: { isMale: boolean }) {
  return (
    <div className="bg-white rounded-2xl shadow-sm border border-stone-200/50 p-12 flex flex-col items-center justify-center text-center gap-4 min-h-[400px]">
      <div className={`w-14 h-14 rounded-full flex items-center justify-center ${isMale ? 'bg-stone-100' : 'bg-emerald-50'}`}>
        <ScanFace className={`w-7 h-7 ${isMale ? 'text-stone-400' : 'text-emerald-400'}`} strokeWidth={1.5} />
      </div>
      <div>
        <p className="text-sm font-medium text-stone-500">顔インサイト</p>
        <p className="text-xs text-stone-400 mt-2 leading-relaxed max-w-sm">
          蓄積した記録から、コンディションの推移やパターンを振り返る機能を準備中です。
          顔カルテに記録をためると、ここで傾向が見えるようになります。
        </p>
      </div>
    </div>
  );
}
